openapi: 3.0.0
info:
  title: OrdersAPI
  version: 1.0.0

paths:
  /orders:
    get:
      summary: Get filtered orders
      operationId: getFilteredOrders
      parameters:
        - in: query
          name: productNo
          required: false
          schema:
            type: string
          description: Product number
        - in: query
          name: page
          description: Page number
          schema:
            type: integer
          required: true
        - in: query
          name: size
          description: Number of items per page
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Successful response with a paginated list of orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  totalPages:
                    type: integer
                  totalElements:
                    type: integer
                  last:
                    type: boolean
                  size:
                    type: integer
                  number:
                    type: integer

  /order:
    get:
      summary: Get order by order ID
      operationId: getOrderById
      parameters:
        - in: query
          name: orderId
          required: false
          schema:
            type: Integer
          description: order id
      responses:
        '200':
          description: Successful response with an order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
        productNo:
          type: string
        customerName:
          type: string
        customerLocation:
          type: string
        customerContactNumber:
          type: string

